# Generated by Django 5.0.6 on 2024-06-29 11:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('car_number', models.CharField(max_length=255)),
                ('car_year', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2100)])),
                ('information', models.TextField(blank=True, null=True)),
                ('tech_passport_number', models.CharField(max_length=255)),
                ('tech_passport_image_front', models.ImageField(blank=True, null=True, upload_to='cars/tech_passport/images')),
                ('tech_passport_image_back', models.ImageField(blank=True, null=True, upload_to='cars/tech_passport/images')),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('electric', 'Electric'), ('petrol_gas', 'Petrol Gas'), ('methane_gas', 'Methane Gas'), ('propane_gas', 'Propane Gas'), ('diesel', 'Diesel'), ('other', 'Other')], default='petrol', max_length=25)),
                ('status', models.CharField(choices=[('active', 'Active'), ('rented', 'Rented'), ('unrepaired', 'Unrepaired'), ('sold', 'Sold')], default='active', max_length=25)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cars',
            },
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars/images')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='car_app.car')),
            ],
            options={
                'db_table': 'car_images',
            },
        ),
    ]
