# Generated by Django 5.0.6 on 2024-07-07 11:45

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0003_alter_car_car_number'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='car',
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
