# Generated by Django 4.2.14 on 2024-07-12 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0005_alter_car_fuel_type'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='car',
            managers=[
            ],
        ),
    ]
