# Generated by Django 5.0.6 on 2024-07-09 11:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_app', '0002_paymentschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentschedule',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='paymentschedule',
            name='penalty_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10),
        ),
    ]
