# Generated by Django 5.0.6 on 2024-06-29 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent_app', '0002_alter_rental_end_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='initial_amount',
            new_name='initial_payment_amount',
        ),
    ]
