# Generated by Django 5.0.6 on 2024-07-01 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_app', '0003_rename_initial_amount_rental_initial_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='rentals/receipt/images'),
        ),
    ]
