# Generated by Django 5.0.6 on 2024-07-09 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent_app', '0003_paymentschedule_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentschedule',
            options={'ordering': ['due_date']},
        ),
    ]
