# Generated by Django 5.0.6 on 2024-07-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_app', '0004_alter_paymentschedule_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentschedule',
            name='paid_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentschedule',
            name='payment_closing_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='due_date',
            field=models.DateTimeField(),
        ),
    ]
