# Generated by Django 5.0.6 on 2024-07-10 04:16

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent_app', '0005_paymentschedule_paid_date_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='paymentschedule',
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
