# Generated by Django 5.0.6 on 2024-07-10 09:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_app', '0006_alter_paymentschedule_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentschedule',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
