# Generated by Django 4.2.14 on 2024-07-10 12:13

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_app', '0007_paymentschedule_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentschedule',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=11),
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='penalty_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=11),
        ),
        migrations.AlterField(
            model_name='rental',
            name='initial_payment_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=11, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))]),
        ),
        migrations.AlterField(
            model_name='rental',
            name='penalty_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=11, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('100.0'))]),
        ),
        migrations.AlterField(
            model_name='rental',
            name='rent_amount',
            field=models.DecimalField(decimal_places=2, max_digits=11, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))]),
        ),
    ]
