# Generated by Django 4.2.14 on 2024-07-10 18:14

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_app', '0008_alter_paymentschedule_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='penalty_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('100.0'))]),
        ),
    ]
