# Generated by Django 4.2.14 on 2024-07-12 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent_app', '0010_alter_rental_options'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='paymentschedule',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='rental',
            managers=[
            ],
        ),
    ]
