# Generated by Django 4.2.14 on 2024-07-12 05:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_app', '0011_alter_paymentschedule_managers_alter_rental_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='passport_image_back',
            field=models.ImageField(blank=True, null=True, upload_to='rentals/passport/images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'heic', 'jpeg', 'gif', 'bmp', 'tiff', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='rental',
            name='passport_image_front',
            field=models.ImageField(blank=True, null=True, upload_to='rentals/passport/images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'heic', 'jpeg', 'gif', 'bmp', 'tiff', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='rental',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='rentals/receipt/images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'heic', 'jpeg', 'gif', 'bmp', 'tiff', 'webp'])]),
        ),
    ]
