# Generated by Django 4.2.14 on 2024-07-13 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rent_app', '0013_alter_rental_passport_image_back_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentschedule',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_schedules', to=settings.AUTH_USER_MODEL),
        ),
    ]
