# Generated by Django 4.2.14 on 2024-07-17 12:38

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_app', '0014_paymentschedule_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='penalty_percentage',
        ),
        migrations.AddField(
            model_name='rental',
            name='currency',
            field=models.CharField(choices=[('uzs', 'UZS'), ('usd', 'USD')], default='UZS', max_length=3),
        ),
        migrations.AddField(
            model_name='rental',
            name='penalty_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))]),
        ),
    ]
