# Generated by Django 4.2.14 on 2024-07-17 12:45

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_app', '0015_remove_rental_penalty_percentage_rental_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='penalty_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=11, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))]),
        ),
    ]
