# Generated by Django 4.2.14 on 2024-07-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_app', '0016_alter_rental_penalty_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='bad_rental',
            field=models.BooleanField(default=False),
        ),
    ]
