# Generated by Django 5.0.7 on 2024-07-30 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_app', '0017_rental_bad_rental'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
